load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:private"])
# Starlark library dependency graph.

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "//js/private:binary_bzl",
        "//js/private:package_bzl",
        "//js/private:test_bzl",
        "//js/private:tree_bzl",
        "//js/private/knip:knip_test_bzl",
        "//js/private/ox:oxfmt_test_bzl",
        "//js/private/ox:oxlint_test_bzl",
        "//js/private/prettier:prettier_test_bzl",
        "//js/private/storybook:storybook_bzl",
        "//js/private/svelte:svelte_kit_bzl",
        "//js/private/svelte:svelte_kit_write_bzl",
        "//js/private/ts:tsc_bzl",
        "//js/private/ts:tsconfig_bzl",
        "//js/private/vite:vite_bzl",
        "//js/private/vite:vite_config_bzl",
        "//js/private/vite:vitest_bzl",
    ],
)

bzl_library(
    name = "providers",
    srcs = ["providers.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "repositories",
    srcs = ["repositories.bzl"],
    visibility = ["//visibility:public"],
    deps = ["//js/private:node_modules_bzl"],
)

exports_files(
    ["defs.bzl"],
    visibility = ["//visibility:public"],
)

exports_files(
    ["providers.bzl"],
    visibility = ["//visibility:public"],
)

exports_files(
    ["repositories.bzl"],
    visibility = ["//visibility:public"],
)
