load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "run-action",
    srcs = [
        "main.go",
    ],
    pure = "on",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//:__subpackages__"],
    deps = [
        "//private/tools/internal/action:lib",
    ],
)
