package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/latticebuild/rules_js/go/filetree"
)

func write(workspace, pkg, source string) (err error) {
	if !filepath.IsAbs(workspace) || !filepath.IsLocal(pkg) {
		return errors.New("expected an absolute workspace and a local package path")
	}
	workspace, err = filetree.RealPath(workspace)
	if err != nil {
		return err
	}
	destination := filepath.Join(workspace, pkg)
	// These subtrees are generated by sync. Other package installations and
	// SvelteKit build outputs belong to their respective owners.
	outputs := []string{
		"node_modules/$app/tsconfig.json",
		"node_modules/$app/tsconfig/service-worker.json",
		"node_modules/$app/types",
		".svelte-kit/types",
	}
	for _, output := range outputs {
		target, err := filetree.Path(workspace, filepath.ToSlash(filepath.Join(pkg, output)))
		if err != nil {
			return err
		}
		if err := filetree.CheckParents(workspace, target); err != nil {
			return err
		}
	}
	source, err = filetree.RealPath(source)
	if err != nil {
		return err
	}
	copier := filetree.NewCopier(nil)
	copier.DeclareRoot(source)
	for _, output := range outputs {
		if err := copier.CheckDestination(workspace, filepath.Join(destination, output)); err != nil {
			return err
		}
	}
	// Staging beside the destination keeps renames on the same filesystem and
	// requires the owning package to exist. No checkout output changes unless
	// every new input has been copied successfully.
	stage, err := os.MkdirTemp(destination, ".svelte-kit-write-")
	if err != nil {
		return err
	}
	defer func() { err = errors.Join(err, os.RemoveAll(stage)) }()
	for _, output := range outputs {
		staged := filepath.Join(stage, output)
		if err := os.MkdirAll(filepath.Dir(staged), 0o755); err != nil {
			return err
		}
		if err := copier.Copy(filepath.Join(source, output), staged); err != nil {
			return err
		}
	}
	for _, output := range outputs {
		target := filepath.Join(destination, output)
		if err := filetree.Prepare(workspace, target); err != nil {
			return err
		}
		if err := os.Rename(filepath.Join(stage, output), target); err != nil {
			return fmt.Errorf("publish %s: %w", target, err)
		}
	}
	return nil
}
