package(default_visibility = ["//visibility:private"])

test_suite(
    name = "test",
    tests = [
        "//go/filetree:unit_test",
        "//go/junit:unit_test",
        "//go/lcov:unit_test",
        "//go/process:unit_test",
        "//go/testenv:unit_test",
        "//js/private/tools/filter-runtime:unit_test",
        "//js/private/tools/run-action:unit_test",
        "//tests:index_test",
        "//tests:lifecycle_test",
        "//tests:reports_test",
        "//tests:tree_test",
        "//tests/pnpm:analysis_test",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "race_test",
    tests = [
        "//go/filetree:unit_race_test",
        "//go/junit:unit_race_test",
        "//go/lcov:unit_race_test",
        "//go/process:unit_race_test",
        "//go/testenv:unit_race_test",
        "//js/private/tools/filter-runtime:unit_race_test",
        "//js/private/tools/run-action:unit_race_test",
    ],
)

filegroup(
    name = "artifacts",
    testonly = True,
    srcs = [
        "//js:defs",
        "//js:providers",
        "//js:repositories",
        "//js/private/tools/run-node-tests",
        "//js/support:action",
        "//js/support:coverage",
        "//js/support:execution",
        "//js/support:fix",
        "//js/support:layout",
        "//js/support:run_action",
        "//js/support:run_fix",
    ],
)
