package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "artifacts",
    srcs = [
        "//examples/ts/check:typecheck",
        "//examples/ts/library:compile",
    ],
)

test_suite(
    name = "test",
    tests = ["//examples/ts/library:emissions_test"],
)
