load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "lib",
    srcs = [
        "run.go",
        "stage.go",
        "stamp.go",
    ],
    importpath = "github.com/latticebuild/rules_js/private/tools/internal/action",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//:__subpackages__"],
    deps = [
        "//go/filetree:lib",
        "@latticebuild_graceproc//:graceproc",
    ],
)

go_test(
    name = "unit_test",
    srcs = [
        "run_test.go",
        "run_unix_test.go",
        "run_windows_test.go",
        "stage_test.go",
        "stage_windows_test.go",
        "stamp_test.go",
    ],
    data = [
        "//private/tools/run-action",
        "@rules_nodejs//nodejs:current_node_runtime",
    ],
    embed = [":lib"],
    env = {
        "NODE_RUNFILES": "$(rlocationpaths @rules_nodejs//nodejs:current_node_runtime)",
        "LATTICEBUILD_TEST_BINARY": "$(rlocationpath //private/tools/run-action)",
    },
    pure = "on",
    race = "off",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//go/filetree:lib",
        "//private/tools/internal/testfs:lib",
        "@io_bazel_rules_go//go/runfiles",
    ],
)

go_test(
    name = "unit_race_test",
    srcs = [
        "run_test.go",
        "run_unix_test.go",
        "run_windows_test.go",
        "stage_test.go",
        "stage_windows_test.go",
        "stamp_test.go",
    ],
    data = [
        "//private/tools/run-action",
        "@rules_nodejs//nodejs:current_node_runtime",
    ],
    embed = [":lib"],
    env = {
        "NODE_RUNFILES": "$(rlocationpaths @rules_nodejs//nodejs:current_node_runtime)",
        "LATTICEBUILD_TEST_BINARY": "$(rlocationpath //private/tools/run-action)",
    },
    pure = "off",
    race = "on",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//go/filetree:lib",
        "//private/tools/internal/testfs:lib",
        "@io_bazel_rules_go//go/runfiles",
    ],
)

test_suite(
    name = "runtime_test",
    tests = [
        ":unit_race_test",
        ":unit_test",
    ],
    visibility = ["//:__subpackages__"],
)
