load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "lib",
    testonly = True,
    srcs = [
        "nodetest.go",
    ],
    importpath = "github.com/latticebuild/rules_js/private/tools/internal/nodetest",
    target_compatible_with = [],
    visibility = ["//:__subpackages__"],
    deps = [
        "//go/arguments:lib",
        "//go/junit:lib",
        "//go/lcov:lib",
        "//go/process:lib",
        "//go/testenv:lib",
    ],
)
