exports_files([
    "package.json",
    "pnpm-workspace.yaml",
])

filegroup(
    name = "artifacts",
    testonly = True,
    srcs = [
        "//examples/action:copy",
        "//examples/basics:hello",
        "//examples/full_tree:tree",
        "//examples/knip:artifacts",
        "//examples/ox:artifacts",
        "//examples/prettier:artifacts",
        "//examples/runtime_tree:tree",
        "//examples/storybook:artifacts",
        "//examples/svelte:artifacts",
        "//examples/ts:artifacts",
        "//examples/vite:artifacts",
    ],
)

test_suite(
    name = "test",
    tests = [
        "//examples/action:scratch_test",
        "//examples/basics:alias_test",
        "//examples/knip:test",
        "//examples/ox:test",
        "//examples/prettier:test",
        "//examples/ts:test",
        "//examples/vite:test",
    ],
)
