load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_test")

go_binary(
    name = "compare-packages",
    srcs = [
        "compare.go",
        "main.go",
    ],
    pure = "on",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    visibility = ["//:__subpackages__"],
    deps = ["//go/filetree:lib"],
)

go_test(
    name = "unit_test",
    srcs = [
        "compare.go",
        "compare_test.go",
        "main.go",
    ],
    pure = "on",
    race = "off",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "@platforms//os:windows": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//go/filetree:lib",
        "//js/private/vite/tools/internal/testfs:lib",
    ],
)

go_test(
    name = "unit_race_test",
    srcs = [
        "compare.go",
        "compare_test.go",
        "main.go",
    ],
    pure = "off",
    race = "on",
    target_compatible_with = select({
        "@platforms//os:linux": [],
        "@platforms//os:macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//go/filetree:lib",
        "//js/private/vite/tools/internal/testfs:lib",
    ],
)

test_suite(
    name = "runtime_test",
    tests = [
        ":unit_race_test",
        ":unit_test",
    ],
    visibility = ["//:__subpackages__"],
)
