"""BUILD definitions and the resolved workspace index consumed by Gazelle."""

load(":graph.bzl", "PLATFORMS")

visibility("//...")

def package_build(module, owner_visibility):
    """Render one physical installation, including any source-only cycle target.

    Args:
        module: Installed record with allocated metadata and resolved graph edges.
        owner_visibility: Canonical visibility label for the installation owner's packages.

    Returns:
        BUILD.bazel text using the toolkit's public rules.
    """
    lines = [
        "# Generated by the pnpm repository rule.",
        "",
        'load(%r, "package_metadata", "purl")' % str(Label("@package_metadata//:defs.bzl")),
    ]
    if module["license"]:
        lines.append('load(%r, "license")' % str(Label("@package_metadata//licenses:defs.bzl")))
    elif module["license_expression"]:
        lines.append('load(%r, "license", "license_kind")' % str(Label("@package_metadata//licenses:defs.bzl")))
    symbols = ['"js_binary"', '"js_package"'] if module["bins"] else ['"js_package"']
    lines.extend([
        "load(%r, %s)" % (str(Label("//js:defs.bzl")), ", ".join(symbols)),
        "",
        "package(default_package_metadata = [%r], default_visibility = [\"//visibility:private\"])" % (":" + module["metadata"]),
        "",
        "package_metadata(",
        "    name = %r," % module["metadata"],
    ])
    if module["license"] or module["license_expression"]:
        lines.append("    attributes = [%r]," % (":" + module["license_target"]))
    purl = 'purl.builder().type("npm")'
    if module["namespace"]:
        purl += ".namespace(%r)" % module["namespace"]
    purl += ".name(%r)" % module["published_name"]
    if module["version"]:
        purl += ".version(%r)" % module["version"]

    # The hub's root filegroup lists every package's metadata.
    lines.extend(["    purl = " + purl + ".build(),", '    visibility = ["//:__pkg__"],', ")"])
    kind = ""
    if module["license"]:
        kind = str(Label("@package_metadata//licenses/spdx:" + module["license"]))
    elif module["license_expression"]:
        kind = ":" + module["license_kind_target"]
        lines.extend([
            "",
            "license_kind(",
            "    name = %r," % module["license_kind_target"],
            "    identifier = %r," % module["license_expression"],
            "    full_name = %r," % module["license_expression"],
            ")",
        ])
    if kind:
        lines.extend([
            "",
            "license(",
            "    name = %r," % module["license_target"],
            "    kind = %r," % kind,
        ])
        if module["license_file"]:
            lines.append("    text = %r," % module["license_file"])
        lines.append(")")

    # Explicit metadata delegates the caller's access to js_binary's symbolic
    # macro; a package default alone does not cross that visibility boundary.
    for _, name, script in module["bins"]:
        lines.extend([
            "",
            "js_binary(",
            "    target_compatible_with = [],",
            "    name = %r," % name,
            "    bin = %r," % script,
            "    data = [%r]," % (":" + module["target"]),
            "    package_metadata = [%r]," % (":" + module["metadata"]),
            '    visibility = ["//:__subpackages__", %r],' % owner_visibility,
            ")",
        ])
    lines.extend([
        "",
        'exports_files(glob(["**/*.json"], exclude = ["node_modules/**"], allow_empty = True), visibility = [%r])' % owner_visibility,
    ])
    for helper in ([True, False] if module["helper"] else [False]):
        lines.extend([
            "",
            "js_package(",
            "    target_compatible_with = [],",
            "    name = %r," % (module["sources"] if helper else module["target"]),
            "    package_name = %r," % module["name"],
            '    package = "package.json",',
            '    srcs = glob(["**"], exclude = ["BUILD", "BUILD.bazel", "node_modules/**", "package.json"], allow_empty = True),',
        ])
        aliases = sorted([install for install in module["installs"] if install != module["rel"]])
        if aliases:
            lines.append("    installs = %r," % aliases)
        if not helper and (module["edges"]["always"] or module["edges"]["when"]):
            lines.append("    deps = %s," % _edges_expression(module["edges"]))
        lines.extend([
            '    visibility = ["//:__subpackages__", %r],' % owner_visibility,
            ")",
        ])
    return "\n".join(lines) + "\n"

def _edges_expression(edges):
    if not edges["when"]:
        return repr(edges["always"])
    branches = ["%r: %r" % (condition, edges["when"][condition]) for condition in sorted(edges["when"])]
    return repr(edges["always"]) + " + select({" + ", ".join(branches) + "})"

def workspace_index(modules, repository, workspace):
    """Expose resolved first-party edges without making Gazelle resolve pnpm.

    Args:
        modules: Described and resolved package records, including workspaces.
        repository: Apparent repository name used in generated dependency labels.
        workspace: Watched YAML and selection metadata, independent of package manifests.

    Returns:
        The JSON-compatible index for first-party generation.
    """
    packages = {}
    for module in modules:
        if not module["workspace"] or not module.get("member", bool(module["target"])):
            continue
        aliases = {}
        canonical = {}
        for name, to in module["imports"].items():
            target = modules[to]
            if target["workspace"] and name != target["name"]:
                aliases[name] = _workspace_label(target["label"], repository)
            else:
                canonical[target["label"]] = True
        alias_labels = {("@" + label if label.startswith("//") else label): True for label in aliases.values() if ("@" + label if label.startswith("//") else label) not in canonical}
        edges = module["edges"]
        packages[module["rel"]] = {
            "aliases": aliases,
            "bindings": {
                name: dict(binding, label = _workspace_label(binding["label"], repository) if binding["label"] else "", binaries = {command: _workspace_label(label, repository) for command, label in binding.get("binaries", {}).items()})
                for name, binding in module.get("development", {}).items()
            },
            "deps": {
                "always": [_workspace_label(label, repository) for label in edges["always"] if label not in alias_labels],
                "when": {condition: [_workspace_label(label, repository) for label in labels if label not in alias_labels] for condition, labels in edges["when"].items()},
            },
            "installs": sorted(module["installs"]),
            "manifest": module["manifest"],
            "name": module["name"],
            "target": module["target"],
        }
    return {
        "installed": {
            _workspace_label(module["label"], repository): module["rel"]
            for module in modules
            if not module["workspace"]
        },
        "packages": packages,
        "platforms": PLATFORMS,
        "repository": repository,
        "version": 3,
        "workspace": workspace,
    }

def _workspace_label(label, repository):
    return label[1:] if label.startswith("@//") else label if label.startswith("@") else "@" + repository + label
