exports_files([
    "go.mod",
    "go.sum",
])

test_suite(
    name = "runtime_test",
    tests = [
        "//go/filetree:runtime_test",
        "//go/junit:runtime_test",
        "//go/lcov:runtime_test",
        "//go/process:runtime_test",
        "//go/testenv:runtime_test",
        "//private/tools/filter-runtime:runtime_test",
        "//private/tools/internal/action:runtime_test",
    ],
    visibility = ["//:__subpackages__"],
)
